started creating setup() function

diff --git a/station b/station
--- a/station
+++ b/station
@@ -2,6 +2,8 @@
 
 # Global Variables
 
+ SYSTEMD_UNIT_FILES="/etc/systemd/system"
+
 #Check for the existence of the /var/tmp/station folder, if it's not there, create it
 STATION_DIR="/var/tmp/station"
 test -d "$STATION_DIR" || mkdir -p "$STATION_DIR"
@@ -66,6 +68,25 @@ function checkUser() {
     return 1
 
 }
+
+function setup() {
+    #Determine if necessary files are present
+    READY_FLAG=0
+
+    [[ -f $SYSTEMD_UNIT_FILES/station-close@.service ]] || READY_FLAG=1
+    [[ -f $SYSTEMD_UNIT_FILES/station-close@.timer ]] || READY_FLAG=1
+    [[ -f $SYSTEMD_UNIT_FILES/station-open@.service ]] || READY_FLAG=1
+    [[ -f $SYSTEMD_UNIT_FILES/station-open@.timer ]] || READY_FLAG=1
+
+    if [[ $READY_FLAG ]]; then
+        echo "ready to go"
+    else    
+        echo "missing neccessary file"
+        exit 1
+    fi
+
+}
+
 #Determine which function the user passed in to the command
 
 case "$1" in
@@ -75,6 +96,10 @@ close)
     exit
     ;;
 open)
+    "$@"
+    exit
+    ;;
+setup)
     "$@"
     exit
     ;;
